files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        fa: fa
        tr: tr
    translate_attributes: '0'
    content_segmentation: '0'
