#+BEGIN_HTML
<a title="Crowdin" target="_blank" href="https://crowdin.com/project/orgzly"><img src="https://d322cqt584bo4o.cloudfront.net/orgzly/localized.svg"></a>
#+END_HTML

* Refactored-happiness


Refactored-happiness is an outliner for taking notes and managing to-do lists.

You can keep notebooks stored in plain-text and have them synchronized
with a directory on your mobile device, SD card, WebDAV server or Dropbox.

Notebooks are saved in /Refactored Hapiness's file format. “Org mode is for
keeping notes, maintaining TODO lists, planning projects, and
authoring documents with a fast and effective plain-text system.”


** Building & testing

If you don't use Android Studio and wish to [[https://developer.android.com/studio/build/building-cmdline.html][build]] and [[https://developer.android.com/studio/test/command-line.html][test]] the app
from command line, the standard set of Gradle tasks is available.  For
example:

- ~./gradlew build~ builds the project and generates APK files
- ~./gradlew connectedAndroidTest~ runs instrumented unit tests

Make sure you [[https://developer.android.com/training/testing/espresso/setup][turn off animations]] for the device you're testing on.

